site_name: FairBench
site_author: Emmanouil (Manios) Krasanakis
repo_url: https://github.com/mever-team/FairBench
copyright: Copyright &copy; 2024 Emmanouil Krasanakis

nav:
    - Home: 'index.md'
    - Overview:
        - 'quick.md'
        - 'reports.md'
        - 'bench.md'
    - Documentation:
        - 'documentation/dimensions.md'
        - 'documentation/reports.md'
        - 'documentation/exploration.md'
        - 'documentation/progress.md'
        - 'documentation/benchmarks.md'
    - Material:
      - 'material/visualization.md'
      - 'material/filters.md'
      - 'material/api.md'
      - 'material/cite.md'

markdown_extensions:
  - admonition
  - mkautodoc
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

theme:
  name: readthedocs
  logo: fairbench.png
  favicon: favicon.ico
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.loading_indicator
    - navigation.scroll
    - content.tabs.link
    - search.suggest
    - toc.integrate
    #- navigation.footer

extra_javascript:
  - mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings

extra_css:
  - theme_extend.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maniospas
      name: Emmanouil (Manios) Krasanakis on GitHub